odom_covariance_override:
  ros__parameters:
    publish_topic_name: hoge                # subscribeするトピック名
    subscribe_topic_name: odometry/gps/raw  # publishするトピック名
    frame_id: hoge                          # publishするトピックのframe_id
    pose_covariance_magnification: 0.5      # pose position covarianceの倍率
    distance_threshold: 0.1                 # 前回からの移動量。この設定値以下の移動量だった場合、pose yaw covarianceは問答無用で2pi^2となる
